### ISSUE TITLE
duplicate code

### ISSUE THREAD

**Issue by melmasri** [felixleopoldo/benchpress#59]
you have to `result_path_mcmc()` functions, see this line 

https://github.com/felixleopoldo/benchpress/blob/7c8eae513c0d4d7dc2e9c6fa96416757295bc515/workflow/rules/evaluation/benchmarks/path_generators.py#L71

and the end of the file

**Comment by felixleopoldo** [comment]
Thanks, one of these can be removed.

**Comment by melmasri** [comment]
see merge request
