### ISSUE TITLE
Estimated graph as input

### ISSUE THREAD

**Issue by felixleopoldo** [felixleopoldo/benchpress#61]
It would be nice with a reserved field name e.g. `input_graph_id`, that could be used to pass an estiamated graph to an algorithm using the algorithms object ID. This is done already in some algorithm modules, but it is not as easy as using a reserved field in the JSON config.
Looking at this implementation of the gobnilp module/rule: https://github.com/felixleopoldo/benchpress/blob/3313d22485566dffbbad88b71fec88f56c59b8fd/workflow/rules/structure_learning_algorithms/gobnilp/rule.smk#L16 `startgraph_file` would correspond to something like `input_graph_file` and `wildcards["startalg"]` here: https://github.com/felixleopoldo/benchpress/blob/3313d22485566dffbbad88b71fec88f56c59b8fd/workflow/rules/structure_learning_algorithms/gobnilp/rule.smk#L6 would be `wildcards["input_graph_id"]` . The idea is to make this feature available seamlessly in any algorithm module by adding the `input_graph_id` field in the config file. 
To do that, something similar to this part of the code should be evaluated for any algorithm having the `input_graph_id` in the config file. https://github.com/felixleopoldo/benchpress/blob/3313d22485566dffbbad88b71fec88f56c59b8fd/workflow/rules/module_strings.py#L60

**Comment by melmasri** [comment]
To solve this issue step by step. First I added an algorithm validation step. Every time some one uses the `input_algorithm_id`, a validation step insures that the configuration for the algorithm under the passed id does not have multiple parameter runs. Meaning, all parameters are at max a list of size 1. 

See this line https://github.com/felixleopoldo/benchpress/blob/9ca7240602cf6c1bd7f0b82d57c178e14253f313/workflow/rules/validate.py#L140
