### ISSUE TITLE
Tetrad json graph structure may have the arrow-tail direction as <-- 

### ISSUE THREAD

**Issue by yasu-sh** [felixleopoldo/benchpress#79]
https://github.com/felixleopoldo/benchpress/blob/c9ea2096f973a63fe3777acab235cd31f42a35b1/workflow/scripts/utils/tetrad_graph_to_adjmat.R#L27

Currently the code has checked the existence of direction so far.
But tetrad with bootstrapping may have output the opposite arrow as edge: "<--".

The code as below may avoid potential problems. 
For my experience, but for bootstrapping, I expect tetrad would make output as one direction as "-->" 
If you have any intentions, feel free to let me know.
```
    # No CIRCLE check.
    isdirected1to2 <- (e$endpoint1 == "TAIL") && (e$endpoint2 == "ARROW")
    isdirected2to1 <- (e$endpoint1 == "ARROW") && (e$endpoint2 == "TAIL")

    if (isdirected1to2) {
      m[node1_ind, node2_ind] <- 1
    } else if (isdirected2to1) {
      m[node2_ind, node1_ind] <- 1
    } else {
      m[node1_ind, node2_ind] <- 1
      m[node2_ind, node1_ind] <- 1
    }
```

**Comment by felixleopoldo** [comment]
I moved the PAG algorithms to the PAGs branch for now until we resolve this.
